// Auto-generated by deploy.js — DO NOT EDIT
// Every deploy gets a unique timestamp → impossible to cache stale data
const LR_BUILD_VERSION = "2026-06-20T23-28-37Z";
const LR_BUILD_TIME = "2026-06-20 23:28:37 UTC";
